# Generated by Django 4.2.20 on 2026-03-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('sector_name', models.CharField(max_length=100)),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'account_sector',
            },
        ),
        migrations.CreateModel(
            name='DistrictCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('district_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'district_creation',
            },
        ),
        migrations.RemoveField(
            model_name='statecreation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statecreation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='statecreation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
