# Generated by Django 4.2.20 on 2026-03-21 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_accountsector_districtcreation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'city_creation',
            },
        ),
        migrations.AddField(
            model_name='accountsector',
            name='acc_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accountsector',
            name='sess_branch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountsector',
            name='sess_company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountsector',
            name='sess_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountsector',
            name='sess_user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountsector',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
