# Generated by Django 4.2.20 on 2026-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_citycreation_accountsector_acc_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsector',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountsector',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsector',
            name='is_delete',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountsector',
            name='sess_branch_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountsector',
            name='sess_company_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountsector',
            name='sess_user_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountsector',
            name='sess_user_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountsector',
            name='session_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
