# Generated by Django 4.2.20 on 2026-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_accountsector_created_accountsector_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.CharField(default='0', max_length=100)),
                ('acc_year', models.CharField(blank=True, max_length=10, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(default='', max_length=50)),
                ('sess_user_type', models.CharField(default='', max_length=50)),
                ('sess_user_id', models.CharField(default='', max_length=50)),
                ('sess_company_id', models.CharField(default='', max_length=50)),
                ('sess_branch_id', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'account_vertical',
            },
        ),
    ]
