# Generated by Django 4.2.20 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0005_accountvertical"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("s_no", models.AutoField(primary_key=True, serialize=False)),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("user_type", models.CharField(max_length=150)),
                ("under_user_type", models.TextField(blank=True, null=True)),
                ("is_active", models.IntegerField(default=1)),
                ("is_delete", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("acc_year", models.CharField(blank=True, max_length=50, null=True)),
                ("session_id", models.CharField(blank=True, max_length=50, null=True)),
                ("sess_user_type", models.CharField(blank=True, max_length=50, null=True)),
                ("sess_user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("sess_company_id", models.CharField(blank=True, max_length=50, null=True)),
                ("sess_branch_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_type",
            },
        ),
    ]
