# Generated by Django 4.2.20 on 2026-03-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0006_usertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCreation",
            fields=[
                ("s_no", models.AutoField(primary_key=True, serialize=False)),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("staff_name", models.CharField(max_length=150)),
                ("staff_id", models.CharField(max_length=100)),
                ("user_type_unique_id", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=20)),
                ("email_id", models.CharField(max_length=150)),
                ("user_name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("password", models.CharField(max_length=255)),
                ("en_password", models.CharField(max_length=255)),
                ("is_active", models.IntegerField(default=1)),
                ("is_delete", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "user"},
        ),
        migrations.CreateModel(
            name="UserScreen",
            fields=[
                ("s_no", models.AutoField(primary_key=True, serialize=False)),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("main_screen_unique_id", models.CharField(max_length=100)),
                ("screen_section_unique_id", models.CharField(blank=True, max_length=100, null=True)),
                ("screen_name", models.CharField(max_length=150)),
                ("folder_name", models.CharField(max_length=150)),
                ("actions", models.TextField(blank=True, null=True)),
                ("icon_name", models.CharField(blank=True, max_length=150, null=True)),
                ("order_no", models.IntegerField(default=0)),
                ("is_active", models.IntegerField(default=1)),
                ("is_delete", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("dashboard_setting_menu", models.CharField(blank=True, max_length=50, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "user_screen"},
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                ("s_no", models.AutoField(primary_key=True, serialize=False)),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("user_type", models.CharField(max_length=50)),
                ("main_screen_unique_id", models.CharField(max_length=100)),
                ("section_unique_id", models.CharField(blank=True, max_length=100, null=True)),
                ("screen_unique_id", models.CharField(max_length=50)),
                ("action_unique_id", models.CharField(max_length=50)),
                ("is_active", models.IntegerField(default=1)),
                ("is_delete", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "user_screen_permission"},
        ),
    ]
