const SCREEN_ROUTE_MAP: Record<string, string> = {
  user_screen: "/admin/user-screen/list",
  main_screen: "/admin/user-screen/list",
  user_type: "/admin/user-type/list",
  user: "/admin/user-creation/list",
  tenant_creation: "/admin/tenant-creation/list",
  tenant: "/admin/tenant-creation/list",
  tenants: "/admin/tenant-creation/list",
  company_creation: "/admin/tenant-creation/list",
  user_permission: "/admin/user-permission/list",
  user_type_permissions: "/admin/user-permission/list",
  state_creation: "/settings/state/list",
  district_creation: "/settings/district/list",
  city_creation: "/settings/city/list",
  account_vertical: "/settings/account-vertical/list",
  account_sector: "/settings/account-sector/list",
  customer_creation: "/settings/customer/list",
  department_creation: "/settings/customer/list",
  item_creation: "/settings/item/list",
  service_engineer: "/settings/service-engineer/list",
  service_engineer_creation: "/settings/service-engineer/list",
  vendor_creation: "/settings/vendor/list",
  insurance_type: "/settings/insurance-type/list",
  insurence_type: "/settings/insurance-type/list",
  product_category: "/settings/product-category/list",
  product_creation: "/settings/product-category/list",
  main_category: "/settings/main-category/list",
  unit_creation: "/settings/unit/list",
  executive_creation: "/settings/executive/list",
  consignee_creation: "/settings/consignee/list",
  pincode_creation: "/settings/pincode/list",
  courier_creation: "/settings/courier/list",
  purchase_order: "/order/purchase-order/list",
  po_form: "/order/purchase-order/list",
  stock_position: "/purchase/stock-position/list",
  stock_positon: "/purchase/stock-position/list",
  consignee_stock_assign: "/stores/consignee-stock/list",
  invoice_and_dc: "/stores/invoice-dc/list",
  invoice_dc: "/stores/invoice-dc/list",
  invoice: "/stores/invoice-dc/list",
  material_qc: "/stores/material-qc/list",
  dispatch: "/stores/dispatch/list",
  operation_approval: "/operation/approval/list",
  doc_apporval_elcot_team: "/operation/approval/list",
  vendor_allocation: "/operation/vendor-allocation/list",
  vendor_allocation_zone: "/operation/vendor-allocation-zone/list",
  vendor_allocation_zone_form: "/operation/vendor-allocation-zone/list",
  vendor_zone_allocation: "/operation/vendor-allocation-zone/list",
  zone_vendor_allocation: "/operation/vendor-allocation-zone/list",
  revendor_allocation: "/operation/revendor-allocation/list",
  re_vendor_allocation: "/operation/revendor-allocation/list",
  delivery_confirmation: "/operation/delivery/list",
  signed_document: "/operation/signed-document/list",
  signed_document_verification: "/operation/signed-document/list",
  signed_document_vertification: "/operation/signed-document/list",
  accounts_approval: "/accounts/approval/list",
  doc_approval_ac_team: "/accounts/approval/list",
  security_deposit: "/accounts/security-deposit/list",
  security_despoist: "/accounts/security-deposit/list",
  customer_payment: "/accounts/customer-payment/list",
  installation: "/service/installation/list",
  bill_creation: "/vendor/bill-creation/list",
  vendor_bill_creation: "/vendor/bill-creation/list",
  vendorpayment: "/vendor/bill-creation/list",
  bill_approval: "/vendor/bill-approval/list",
  vendor_bill_approval: "/vendor/bill-approval/list",
  accounts_bill_entry: "/vendor/accounts-bill-entry/list",
  accounts_team_bill_entry: "/vendor/accounts-bill-entry/list",
  accounts_bill_approval: "/vendor/accounts-bill-approval/list",
  accounts_team_bill_approval: "/vendor/accounts-bill-approval/list",
  finance_approval: "/vendor/accounts-bill-approval/list",
  management_approval: "/vendor/management-bill-approval/list",
  management_team_bill_approval: "/vendor/management-bill-approval/list",
  payment_transaction: "/vendor/payment-transaction/list",
  payment_transaction_form: "/vendor/payment-transaction/list",
  accounts_vendor_approval: "/vendor/payment-transaction/list",
  bank_details: "/vendor/bank-details/list",
  onsite_engineer_payment: "/vendor/onsite-engineer-payment/list",
  onsite_enggineer_payment: "/vendor/onsite-engineer-payment/list",
  onsite_engineer: "/vendor/onsite-engineer-payment/list",
  revisit_payment: "/vendor/revisit-payment/list",
  revist_payment: "/vendor/revisit-payment/list",
  revisit_payemnt: "/vendor/revisit-payment/list",
  revist_payemnt: "/vendor/revisit-payment/list",
  revisit_vendor_payment: "/vendor/revisit-payment/list",
  po_wise_reports: "/reports/po-wise",
  po_wise_report: "/reports/po-wise",
  completed_po: "/reports/completed-po",
  completed_po_report: "/reports/completed-po",
  completed_purchase_order: "/reports/completed-po",
  overdue_incomplete_po: "/reports/overdue-incomplete-po",
  overdue_incomplete_po_report: "/reports/overdue-incomplete-po",
  overdue_incomplete_po_reports: "/reports/overdue-incomplete-po",
  overdue_incomplete_purchase_order: "/reports/overdue-incomplete-po",
  overdue_incomplete_purchase_order_report: "/reports/overdue-incomplete-po",
  payment_process_report: "/reports/payment-process-report",
  payment_process_reports: "/reports/payment-process-report",
  vendor_payment_report: "/reports/payment-process-report",
  vendor_payment_reports: "/reports/payment-process-report",
  po_wise_documents: "/documents/po-wise",
  po_wise_document: "/documents/po-wise",
};

function normalize(value: string) {
  return (value || "")
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export function resolveMenuPath(screenName: string, folderName: string) {
  const byFolder = SCREEN_ROUTE_MAP[normalize(folderName)];
  if (byFolder) return byFolder;

  const byName = SCREEN_ROUTE_MAP[normalize(screenName)];
  if (byName) return byName;

  return "";
}
